.ALIASES
R_R1            R1(1=N00673 2=N01131 )
R_R2            R2(1=N00673 2=N00637 )
R_R             R(1=N01131 2=N00756 )
C_C1            C1(1=N00756 2=N00637 )
X_U3A           U3A(+=GND -=N00756 V+=VCC+ V-=VCC- OUT=N00637 )
V_V1            V1(+=GND -=VCC- )
X_U4A           U4A(+=N00673 -=GND V+=VCC+ V-=VCC- OUT=N01131 )
V_V3            V3(+=VCC+ -=GND )
_    _(VCC-=VCC-)
_    _(VCC+=VCC+)
_    _(GND=GND)
.ENDALIASES
